/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehicleparkingmenegement;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;

public class DeletePage extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form DeletePage
     */
    public String d;

    public DeletePage(String s) {
        d = s;
        initComponents();
        setVisible(true);
        setTitle("Vehicle Parking Delete Page");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        informationMethod();

        deleteJButton.addActionListener(this);
        cancelJButton.addActionListener(this);
        exitJMenuItem.addActionListener(this);
        helpJMenuItem.addActionListener(this);
        homeJMenuItem.addActionListener(this);

    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == deleteJButton) {

            setVisible(false);
            Conection ob1 = new Conection();
            String query = "UPDATE informationlist SET status = 'NO' WHERE Sl = '" + d + "';";
            try {

                ob1.stmt.executeUpdate(query);
                ob1.con.close();
            } catch (SQLException ev) {
                ev.printStackTrace();
            }

        }

        if (e.getSource() == cancelJButton) {

            setVisible(false);

        }
        if (e.getSource() == exitJMenuItem) {

            System.exit(0);

        }
        if (e.getSource() == helpJMenuItem) {

            
            JOptionPane.showMessageDialog(rootPane,"ABOUT THIS PAGE...\n"
                    + "'DELETE' button will discharge your selected vehicle.\n"
                    + "'CANCEL' button will cancel for discharging & moves into the previous page.\n");
            

        }
        if (e.getSource() == homeJMenuItem) {

            setVisible(false);
            
            MainPage mainPage = new MainPage();
        }
    }

    private void informationMethod() {
        String query1 = "SELECT * FROM `informationlist` WHERE Sl = '" + d + "'";
        Conection ob3 = new Conection();
        try {

            ob3.rs = ob3.stmt.executeQuery(query1);
            String contact = "";
            String sl = "";
            String nm = "";
            String add = "";
            String mb = "";
            String lNo = "";
            String vNo = "";
            String tD = "";
            String status = "";
            
            while (ob3.rs.next()) {

                sl = ob3.rs.getString(1);
                nm = ob3.rs.getString(2);
                add = ob3.rs.getString(3);
                mb = ob3.rs.getString(4);
                lNo = ob3.rs.getString(5);

                vNo = ob3.rs.getString(6);
                tD = ob3.rs.getString(7);
                status = ob3.rs.getString(8);
            }

            
            serialShowJLabel.setText(sl);
            nameShowJLabel.setText(nm);
            addressShowJLabel.setText(add);
            mobileShowJLabel.setText(mb);
            licenseShowJLabel.setText(lNo);
            vehicleShowJLabel.setText(vNo);
            parkingTimeDateShowJLabel.setText(tD);
            statusShowJLabel.setText(status);

        } catch (SQLException ev) {
            ev.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundJPanel = new javax.swing.JPanel();
        vehicleParkingMenegementJLabel = new javax.swing.JLabel();
        footerJLabel = new javax.swing.JLabel();
        buttonJPanel = new javax.swing.JPanel();
        deleteJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();
        questionJLabel = new javax.swing.JLabel();
        informationJPanel = new javax.swing.JPanel();
        serialJLabel = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        addressJLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        licenseJLabel = new javax.swing.JLabel();
        vehicleJLabel = new javax.swing.JLabel();
        parkingTimeDateJLabel = new javax.swing.JLabel();
        statusJLabel = new javax.swing.JLabel();
        serialShowJLabel = new javax.swing.JLabel();
        nameShowJLabel = new javax.swing.JLabel();
        addressShowJLabel = new javax.swing.JLabel();
        mobileShowJLabel = new javax.swing.JLabel();
        licenseShowJLabel = new javax.swing.JLabel();
        vehicleShowJLabel = new javax.swing.JLabel();
        parkingTimeDateShowJLabel = new javax.swing.JLabel();
        statusShowJLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitJMenuItem = new javax.swing.JMenuItem();
        homeJMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        helpJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundJPanel.setBackground(new java.awt.Color(0, 255, 255));
        backgroundJPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 204)));

        vehicleParkingMenegementJLabel.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        vehicleParkingMenegementJLabel.setForeground(new java.awt.Color(153, 0, 153));
        vehicleParkingMenegementJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vehicleParkingMenegementJLabel.setText("VEHICLE PARKING MENEGEMENT");
        vehicleParkingMenegementJLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 204)));

        footerJLabel.setBackground(new java.awt.Color(0, 255, 153));
        footerJLabel.setFont(new java.awt.Font("Yu Mincho Light", 3, 14)); // NOI18N
        footerJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footerJLabel.setText("copyright@sabuj&nurul");

        buttonJPanel.setBackground(new java.awt.Color(255, 255, 0));
        buttonJPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(204, 0, 0)));

        deleteJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vehicleparkingmenegement/delete.png"))); // NOI18N
        deleteJButton.setText("DELETE");

        cancelJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vehicleparkingmenegement/close.jpeg"))); // NOI18N
        cancelJButton.setText("CANCEL");

        javax.swing.GroupLayout buttonJPanelLayout = new javax.swing.GroupLayout(buttonJPanel);
        buttonJPanel.setLayout(buttonJPanelLayout);
        buttonJPanelLayout.setHorizontalGroup(
            buttonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonJPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(deleteJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        buttonJPanelLayout.setVerticalGroup(
            buttonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonJPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(buttonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(deleteJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        questionJLabel.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        questionJLabel.setForeground(new java.awt.Color(204, 0, 0));
        questionJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionJLabel.setText("What do you want to do ??");
        questionJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        informationJPanel.setBackground(new java.awt.Color(0, 204, 204));
        informationJPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 204)));

        serialJLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        serialJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        serialJLabel.setText("SERIAL NO      ");
        serialJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nameJLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        nameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameJLabel.setText("NAME");
        nameJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        addressJLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        addressJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addressJLabel.setText("ADDRESS");
        addressJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("MOBILE NO");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        licenseJLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        licenseJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        licenseJLabel.setText("LICENSE NO");
        licenseJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        vehicleJLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        vehicleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vehicleJLabel.setText("VEHICLE NO");
        vehicleJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        parkingTimeDateJLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        parkingTimeDateJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        parkingTimeDateJLabel.setText("PARKING TIME&DATE");
        parkingTimeDateJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        statusJLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        statusJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusJLabel.setText("STATUS");
        statusJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        serialShowJLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        serialShowJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        serialShowJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nameShowJLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        nameShowJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameShowJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        addressShowJLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        addressShowJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addressShowJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        mobileShowJLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        mobileShowJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mobileShowJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        licenseShowJLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        licenseShowJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        licenseShowJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        vehicleShowJLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        vehicleShowJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vehicleShowJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        parkingTimeDateShowJLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        parkingTimeDateShowJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        parkingTimeDateShowJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        statusShowJLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        statusShowJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusShowJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout informationJPanelLayout = new javax.swing.GroupLayout(informationJPanel);
        informationJPanel.setLayout(informationJPanelLayout);
        informationJPanelLayout.setHorizontalGroup(
            informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informationJPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informationJPanelLayout.createSequentialGroup()
                        .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(parkingTimeDateJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statusJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, informationJPanelLayout.createSequentialGroup()
                                .addComponent(vehicleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE))
                    .addGroup(informationJPanelLayout.createSequentialGroup()
                        .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(licenseJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serialJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nameShowJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addressShowJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mobileShowJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(licenseShowJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vehicleShowJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(parkingTimeDateShowJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(statusShowJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                    .addComponent(serialShowJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
        informationJPanelLayout.setVerticalGroup(
            informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialShowJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameShowJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressShowJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobileShowJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseShowJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenseJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleShowJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parkingTimeDateShowJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parkingTimeDateJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statusJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statusShowJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        serialJLabel.getAccessibleContext().setAccessibleName("SERIAL");

        javax.swing.GroupLayout backgroundJPanelLayout = new javax.swing.GroupLayout(backgroundJPanel);
        backgroundJPanel.setLayout(backgroundJPanelLayout);
        backgroundJPanelLayout.setHorizontalGroup(
            backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vehicleParkingMenegementJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
            .addComponent(footerJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundJPanelLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(questionJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(informationJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71))
        );
        backgroundJPanelLayout.setVerticalGroup(
            backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundJPanelLayout.createSequentialGroup()
                .addComponent(vehicleParkingMenegementJLabel)
                .addGap(23, 23, 23)
                .addComponent(informationJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questionJLabel)
                .addGap(18, 18, 18)
                .addComponent(buttonJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footerJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("File");

        exitJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        exitJMenuItem.setText("Exit");
        jMenu1.add(exitJMenuItem);

        homeJMenuItem.setText("Home");
        jMenu1.add(homeJMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        helpJMenuItem.setText("Help");
        jMenu2.add(helpJMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressJLabel;
    private javax.swing.JLabel addressShowJLabel;
    private javax.swing.JPanel backgroundJPanel;
    private javax.swing.JPanel buttonJPanel;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JMenuItem exitJMenuItem;
    private javax.swing.JLabel footerJLabel;
    private javax.swing.JMenuItem helpJMenuItem;
    private javax.swing.JMenuItem homeJMenuItem;
    private javax.swing.JPanel informationJPanel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel licenseJLabel;
    private javax.swing.JLabel licenseShowJLabel;
    private javax.swing.JLabel mobileShowJLabel;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JLabel nameShowJLabel;
    private javax.swing.JLabel parkingTimeDateJLabel;
    private javax.swing.JLabel parkingTimeDateShowJLabel;
    private javax.swing.JLabel questionJLabel;
    private javax.swing.JLabel serialJLabel;
    private javax.swing.JLabel serialShowJLabel;
    private javax.swing.JLabel statusJLabel;
    private javax.swing.JLabel statusShowJLabel;
    private javax.swing.JLabel vehicleJLabel;
    private javax.swing.JLabel vehicleParkingMenegementJLabel;
    private javax.swing.JLabel vehicleShowJLabel;
    // End of variables declaration//GEN-END:variables

}
