/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehicleparkingmenegement;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class ViewPage extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form ViewPage
     */
    ViewPage() {
        initComponents();
        setVisible(true);
        setTitle("Vehicle Parking Add Page");
        setLocationRelativeTo(null);

        tableMethod();

        backJButton.addActionListener(this);
        exitJMenuItem.addActionListener(this);
        helpJMenuItem.addActionListener(this);
        homeJMenuItem.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == backJButton) {
            backMethod();
        }
        if (e.getSource() == exitJMenuItem) {
            System.exit(0);
        }

        if (e.getSource() == helpJMenuItem) {
            JOptionPane.showMessageDialog(rootPane, "ABOUT THIS PAGE...\n"
                    + "'BACK' button will move into previous page.\n"
                    + "below table shows the information of parked vehicles.\n"
            );
        }
        if (e.getSource() == homeJMenuItem) {

            setVisible(false);

            MainPage mainPage = new MainPage();
        }
    }

    private void backMethod() {
        setVisible(false);
        MainPage mainPage = new MainPage();
    }

    private void tableMethod() {

        String[] sl = new String[100];
        String[] nm = new String[100];
        String[] add = new String[100];
        String[] mb = new String[100];
        String[] lNo = new String[100];
        String[] vNo = new String[100];
        String[] tD = new String[100];
        String[] status = new String[100];

        int i = 0;
        int len = 0;

        Conection ob1 = new Conection();
        String query = "Select * FROM informationlist";
        try {

            ob1.rs = ob1.stmt.executeQuery(query);

            while (ob1.rs.next()) {

                sl[i] = ob1.rs.getString(1);
                nm[i] = ob1.rs.getString(2);
                add[i] = ob1.rs.getString(3);
                mb[i] = ob1.rs.getString(4);
                lNo[i] = ob1.rs.getString(5);
                vNo[i] = ob1.rs.getString(6);
                tD[i] = ob1.rs.getString(7);
                status[i] = ob1.rs.getString(8);

                i++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        len = i;

        for (int j = 0; j < len; j++) {
            Object[] row = {sl[j], nm[j], add[j], mb[j], lNo[j], vNo[j], tD[j], status[j]};
            DefaultTableModel model = (DefaultTableModel) informationJTable.getModel();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundJPanel = new javax.swing.JPanel();
        vehicleParkingMenegementJLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        footerJLabel = new javax.swing.JLabel();
        titleJLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        informationJTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitJMenuItem = new javax.swing.JMenuItem();
        homeJMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        helpJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundJPanel.setBackground(new java.awt.Color(0, 255, 255));
        backgroundJPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 255)));

        vehicleParkingMenegementJLabel.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        vehicleParkingMenegementJLabel.setForeground(new java.awt.Color(153, 0, 153));
        vehicleParkingMenegementJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vehicleParkingMenegementJLabel.setText("VEHICLE PARKING MENEGEMENT");
        vehicleParkingMenegementJLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 204)));

        backJButton.setBackground(new java.awt.Color(255, 255, 255));
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vehicleparkingmenegement/back.png"))); // NOI18N
        backJButton.setText("BACK");

        footerJLabel.setBackground(new java.awt.Color(0, 255, 153));
        footerJLabel.setFont(new java.awt.Font("Yu Mincho Light", 3, 14)); // NOI18N
        footerJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footerJLabel.setText("copyright@sabuj&nurul");

        titleJLabel.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        titleJLabel.setForeground(new java.awt.Color(255, 0, 51));
        titleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        titleJLabel.setText("This is the list and imformation of parked vehicle in the parking place");
        titleJLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        titleJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        informationJTable.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(153, 0, 204)));
        informationJTable.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        informationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SERIAL", "NAME", "ADDRESS", "MOBILE NO", "LICENSE NO", "VEHICLE NO", "TIME AND DATE", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        informationJTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        informationJTable.setAutoscrolls(false);
        informationJTable.setEditingRow(2);
        informationJTable.setFillsViewportHeight(true);
        informationJTable.setRowHeight(25);
        informationJTable.setRowMargin(3);
        informationJTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane2.setViewportView(informationJTable);

        javax.swing.GroupLayout backgroundJPanelLayout = new javax.swing.GroupLayout(backgroundJPanel);
        backgroundJPanel.setLayout(backgroundJPanelLayout);
        backgroundJPanelLayout.setHorizontalGroup(
            backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vehicleParkingMenegementJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundJPanelLayout.createSequentialGroup()
                .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundJPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(backgroundJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(footerJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        backgroundJPanelLayout.setVerticalGroup(
            backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundJPanelLayout.createSequentialGroup()
                .addComponent(vehicleParkingMenegementJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addGap(107, 107, 107)
                .addComponent(footerJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("File");

        exitJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        exitJMenuItem.setText("Exit");
        jMenu1.add(exitJMenuItem);

        homeJMenuItem.setText("Home");
        jMenu1.add(homeJMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        helpJMenuItem.setText("Help");
        jMenu2.add(helpJMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JPanel backgroundJPanel;
    private javax.swing.JMenuItem exitJMenuItem;
    private javax.swing.JLabel footerJLabel;
    private javax.swing.JMenuItem helpJMenuItem;
    private javax.swing.JMenuItem homeJMenuItem;
    private javax.swing.JTable informationJTable;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JLabel vehicleParkingMenegementJLabel;
    // End of variables declaration//GEN-END:variables

}
