/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mcqexamproject;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author F.C
 */
public class ExamJFrame extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form ExamJFrame1
     */
    public ExamJFrame() {
        initComponents();
        setTitle("Question Add and Exam..");
        setResizable(false);
        setVisible(true);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancleJButton = new javax.swing.JButton();
        skipJButton = new javax.swing.JButton();
        okJButton = new javax.swing.JButton();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        QuestionJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MarksJLabel = new javax.swing.JLabel();
        MarksTitleJLabel = new javax.swing.JLabel();
        NegetiveMarksJLabel = new javax.swing.JLabel();
        NegetiveMarksTitleJLabel = new javax.swing.JLabel();
        numberOfQuestionJLabel = new javax.swing.JLabel();
        numberOfQuestionLimitTitleJLabel = new javax.swing.JLabel();
        numberOfQuestionLimitJLabel = new javax.swing.JLabel();
        numberOfQuestionTitleJLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancleJButton.setText("CANCLE");
        getContentPane().add(cancleJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 277, -1, -1));

        skipJButton.setText("SKIP");
        getContentPane().add(skipJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 277, -1, -1));

        okJButton.setText("OK");
        getContentPane().add(okJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 277, -1, -1));

        jCheckBox4.setText("jCheckBox1");
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 215, -1, -1));

        jCheckBox3.setText("jCheckBox1");
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 215, -1, -1));

        jCheckBox2.setText("jCheckBox1");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 160, -1, -1));

        jCheckBox1.setText("jCheckBox1");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        QuestionJLabel.setText("jLabel2");
        getContentPane().add(QuestionJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 85, 438, 32));

        jLabel1.setText("1 .");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, -1, 32));

        MarksJLabel.setText("jLabel5");
        getContentPane().add(MarksJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 43, 63, 36));

        MarksTitleJLabel.setText("YOUR MARKS IS  :");
        getContentPane().add(MarksTitleJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 43, 104, 36));

        NegetiveMarksJLabel.setText("jLabel7");
        getContentPane().add(NegetiveMarksJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 43, 45, 36));

        NegetiveMarksTitleJLabel.setText("NEGETIVE MARKING PER QUESTION  :");
        getContentPane().add(NegetiveMarksTitleJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, 208, 36));

        numberOfQuestionJLabel.setText("jLabel9");
        getContentPane().add(numberOfQuestionJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 45, 25));

        numberOfQuestionLimitTitleJLabel.setText("OF QUESTION LIMIT  :");
        getContentPane().add(numberOfQuestionLimitTitleJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 120, 25));

        numberOfQuestionLimitJLabel.setText("jLabel11");
        getContentPane().add(numberOfQuestionLimitJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 44, 25));

        numberOfQuestionTitleJLabel.setText("QUESTION  NUMBER  :");
        getContentPane().add(numberOfQuestionTitleJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 120, 25));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mcqexamproject/img.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MarksJLabel;
    private javax.swing.JLabel MarksTitleJLabel;
    private javax.swing.JLabel NegetiveMarksJLabel;
    private javax.swing.JLabel NegetiveMarksTitleJLabel;
    private javax.swing.JLabel QuestionJLabel;
    private javax.swing.JButton cancleJButton;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel numberOfQuestionJLabel;
    private javax.swing.JLabel numberOfQuestionLimitJLabel;
    private javax.swing.JLabel numberOfQuestionLimitTitleJLabel;
    private javax.swing.JLabel numberOfQuestionTitleJLabel;
    private javax.swing.JButton okJButton;
    private javax.swing.JButton skipJButton;
    // End of variables declaration//GEN-END:variables

}
