/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mcqexamproject;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author F.C
 */
public class QuestionAddAndExam extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form QuestionSetAndExam
     */
    public QuestionAddAndExam() {
        initComponents();
        setTitle("Question Add and Exam..");
        setResizable(false);
        setVisible(true);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        questionAddJButton.addActionListener(this);
        examJButton.addActionListener(this);
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==questionAddJButton){
            setVisible(false);
            QuestionSetInstruction questionSetInstruction = new QuestionSetInstruction();
        }
        
        if(e.getSource()==examJButton){
            
            setVisible(false);
            ExamJFrame examJFrame = new ExamJFrame();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionAddJButton = new javax.swing.JButton();
        examJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        questionAddJButton.setText("Question Add");
        questionAddJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionAddJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(questionAddJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 137, -1, -1));

        examJButton.setText("Exam");
        getContentPane().add(examJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 137, 97, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mcqexamproject/img.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void questionAddJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionAddJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questionAddJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionAddAndExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionAddAndExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionAddAndExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionAddAndExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionAddAndExam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton examJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton questionAddJButton;
    // End of variables declaration//GEN-END:variables

}
