/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package birthdaywishsoftware;

import java.util.concurrent.TimeUnit;

/**
 *
 * @author Sabuj Chandra Paul
 */
public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    String name = "";

    public Frame2(String s) {
        initComponents();

        name = s;

        System.out.println("" + s);
        Runner r1 = new Runner();
        r1.start();

    }

    class Runner extends Thread {

        @Override
        public void run() {
            setVisible(true);
            setTitle("BIRTHDAY WISH SOFTWARE, Frame : 2 ..");
            setLocationRelativeTo(null);
            setResizable(false);
            setDefaultCloseOperation(EXIT_ON_CLOSE);

            try {
                Thread.sleep(10000);
                for (int i = 0; i < 3; i++) {
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/h.gif")));
                    System.out.println("" + name+">"+i);
                    Thread.sleep(1000);
                }
            } catch (InterruptedException ex) {
                ex.printStackTrace();
                //Logger.getLogger(Runner.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJPanel = new javax.swing.JPanel();
        firstJPanel = new javax.swing.JPanel();
        aJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cJPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dJPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        eJPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        fJPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        gJPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        hJPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        iJPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        secondJPanel = new javax.swing.JPanel();
        jJPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        kJPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lJPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        mJPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        nJPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        oJPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pJPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        qJPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        rJPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        thirdJPanel = new javax.swing.JPanel();
        sJPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        tJPanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        uJPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        vJPanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        wJPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        xJPanel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        yJPanel = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        zJPanel = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainJPanel.setBackground(new java.awt.Color(255, 255, 0));

        firstJPanel.setBackground(new java.awt.Color(0, 204, 204));

        aJPanel.setBackground(new java.awt.Color(204, 0, 204));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/a.gif"))); // NOI18N

        javax.swing.GroupLayout aJPanelLayout = new javax.swing.GroupLayout(aJPanel);
        aJPanel.setLayout(aJPanelLayout);
        aJPanelLayout.setHorizontalGroup(
            aJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        aJPanelLayout.setVerticalGroup(
            aJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bJPanel.setBackground(new java.awt.Color(204, 0, 204));
        bJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/b.gif"))); // NOI18N

        javax.swing.GroupLayout bJPanelLayout = new javax.swing.GroupLayout(bJPanel);
        bJPanel.setLayout(bJPanelLayout);
        bJPanelLayout.setHorizontalGroup(
            bJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );
        bJPanelLayout.setVerticalGroup(
            bJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cJPanel.setBackground(new java.awt.Color(204, 0, 204));
        cJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/c.gif"))); // NOI18N

        javax.swing.GroupLayout cJPanelLayout = new javax.swing.GroupLayout(cJPanel);
        cJPanel.setLayout(cJPanelLayout);
        cJPanelLayout.setHorizontalGroup(
            cJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        cJPanelLayout.setVerticalGroup(
            cJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dJPanel.setBackground(new java.awt.Color(204, 0, 204));
        dJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/d.gif"))); // NOI18N

        javax.swing.GroupLayout dJPanelLayout = new javax.swing.GroupLayout(dJPanel);
        dJPanel.setLayout(dJPanelLayout);
        dJPanelLayout.setHorizontalGroup(
            dJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        dJPanelLayout.setVerticalGroup(
            dJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        eJPanel.setBackground(new java.awt.Color(204, 0, 204));
        eJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/e.gif"))); // NOI18N

        javax.swing.GroupLayout eJPanelLayout = new javax.swing.GroupLayout(eJPanel);
        eJPanel.setLayout(eJPanelLayout);
        eJPanelLayout.setHorizontalGroup(
            eJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        eJPanelLayout.setVerticalGroup(
            eJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fJPanel.setBackground(new java.awt.Color(204, 0, 204));
        fJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/f.gif"))); // NOI18N

        javax.swing.GroupLayout fJPanelLayout = new javax.swing.GroupLayout(fJPanel);
        fJPanel.setLayout(fJPanelLayout);
        fJPanelLayout.setHorizontalGroup(
            fJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        fJPanelLayout.setVerticalGroup(
            fJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        gJPanel.setBackground(new java.awt.Color(204, 0, 204));
        gJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/g.gif"))); // NOI18N

        javax.swing.GroupLayout gJPanelLayout = new javax.swing.GroupLayout(gJPanel);
        gJPanel.setLayout(gJPanelLayout);
        gJPanelLayout.setHorizontalGroup(
            gJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        gJPanelLayout.setVerticalGroup(
            gJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        hJPanel.setBackground(new java.awt.Color(204, 0, 204));
        hJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/h.gif"))); // NOI18N

        javax.swing.GroupLayout hJPanelLayout = new javax.swing.GroupLayout(hJPanel);
        hJPanel.setLayout(hJPanelLayout);
        hJPanelLayout.setHorizontalGroup(
            hJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        hJPanelLayout.setVerticalGroup(
            hJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        iJPanel.setBackground(new java.awt.Color(204, 0, 204));
        iJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/i.gif"))); // NOI18N

        javax.swing.GroupLayout iJPanelLayout = new javax.swing.GroupLayout(iJPanel);
        iJPanel.setLayout(iJPanelLayout);
        iJPanelLayout.setHorizontalGroup(
            iJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        iJPanelLayout.setVerticalGroup(
            iJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout firstJPanelLayout = new javax.swing.GroupLayout(firstJPanel);
        firstJPanel.setLayout(firstJPanelLayout);
        firstJPanelLayout.setHorizontalGroup(
            firstJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        firstJPanelLayout.setVerticalGroup(
            firstJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firstJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(aJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(cJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(dJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(eJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(gJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(hJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(iJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap())
        );

        secondJPanel.setBackground(new java.awt.Color(0, 204, 204));

        jJPanel.setBackground(new java.awt.Color(204, 0, 204));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/j.gif"))); // NOI18N

        javax.swing.GroupLayout jJPanelLayout = new javax.swing.GroupLayout(jJPanel);
        jJPanel.setLayout(jJPanelLayout);
        jJPanelLayout.setHorizontalGroup(
            jJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        jJPanelLayout.setVerticalGroup(
            jJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        kJPanel.setBackground(new java.awt.Color(204, 0, 204));
        kJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/k.gif"))); // NOI18N

        javax.swing.GroupLayout kJPanelLayout = new javax.swing.GroupLayout(kJPanel);
        kJPanel.setLayout(kJPanelLayout);
        kJPanelLayout.setHorizontalGroup(
            kJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        kJPanelLayout.setVerticalGroup(
            kJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lJPanel.setBackground(new java.awt.Color(204, 0, 204));
        lJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/l.gif"))); // NOI18N

        javax.swing.GroupLayout lJPanelLayout = new javax.swing.GroupLayout(lJPanel);
        lJPanel.setLayout(lJPanelLayout);
        lJPanelLayout.setHorizontalGroup(
            lJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        lJPanelLayout.setVerticalGroup(
            lJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mJPanel.setBackground(new java.awt.Color(204, 0, 204));
        mJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/m.gif"))); // NOI18N

        javax.swing.GroupLayout mJPanelLayout = new javax.swing.GroupLayout(mJPanel);
        mJPanel.setLayout(mJPanelLayout);
        mJPanelLayout.setHorizontalGroup(
            mJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );
        mJPanelLayout.setVerticalGroup(
            mJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        nJPanel.setBackground(new java.awt.Color(204, 0, 204));
        nJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/n.gif"))); // NOI18N

        javax.swing.GroupLayout nJPanelLayout = new javax.swing.GroupLayout(nJPanel);
        nJPanel.setLayout(nJPanelLayout);
        nJPanelLayout.setHorizontalGroup(
            nJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        nJPanelLayout.setVerticalGroup(
            nJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        oJPanel.setBackground(new java.awt.Color(204, 0, 204));
        oJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/o.gif"))); // NOI18N

        javax.swing.GroupLayout oJPanelLayout = new javax.swing.GroupLayout(oJPanel);
        oJPanel.setLayout(oJPanelLayout);
        oJPanelLayout.setHorizontalGroup(
            oJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        oJPanelLayout.setVerticalGroup(
            oJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        pJPanel.setBackground(new java.awt.Color(204, 0, 204));
        pJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/p.gif"))); // NOI18N

        javax.swing.GroupLayout pJPanelLayout = new javax.swing.GroupLayout(pJPanel);
        pJPanel.setLayout(pJPanelLayout);
        pJPanelLayout.setHorizontalGroup(
            pJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        pJPanelLayout.setVerticalGroup(
            pJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        qJPanel.setBackground(new java.awt.Color(204, 0, 204));
        qJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/q.gif"))); // NOI18N

        javax.swing.GroupLayout qJPanelLayout = new javax.swing.GroupLayout(qJPanel);
        qJPanel.setLayout(qJPanelLayout);
        qJPanelLayout.setHorizontalGroup(
            qJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        qJPanelLayout.setVerticalGroup(
            qJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        rJPanel.setBackground(new java.awt.Color(204, 0, 204));
        rJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/r.gif"))); // NOI18N

        javax.swing.GroupLayout rJPanelLayout = new javax.swing.GroupLayout(rJPanel);
        rJPanel.setLayout(rJPanelLayout);
        rJPanelLayout.setHorizontalGroup(
            rJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );
        rJPanelLayout.setVerticalGroup(
            rJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout secondJPanelLayout = new javax.swing.GroupLayout(secondJPanel);
        secondJPanel.setLayout(secondJPanelLayout);
        secondJPanelLayout.setHorizontalGroup(
            secondJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secondJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(oJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(qJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        secondJPanelLayout.setVerticalGroup(
            secondJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(secondJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(lJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(mJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(nJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(pJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(qJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(rJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap())
        );

        thirdJPanel.setBackground(new java.awt.Color(0, 204, 204));

        sJPanel.setBackground(new java.awt.Color(204, 0, 204));
        sJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/s.gif"))); // NOI18N

        javax.swing.GroupLayout sJPanelLayout = new javax.swing.GroupLayout(sJPanel);
        sJPanel.setLayout(sJPanelLayout);
        sJPanelLayout.setHorizontalGroup(
            sJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        sJPanelLayout.setVerticalGroup(
            sJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tJPanel.setBackground(new java.awt.Color(204, 0, 204));
        tJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/t.gif"))); // NOI18N

        javax.swing.GroupLayout tJPanelLayout = new javax.swing.GroupLayout(tJPanel);
        tJPanel.setLayout(tJPanelLayout);
        tJPanelLayout.setHorizontalGroup(
            tJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        tJPanelLayout.setVerticalGroup(
            tJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        uJPanel.setBackground(new java.awt.Color(204, 0, 204));
        uJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/U.gif"))); // NOI18N
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout uJPanelLayout = new javax.swing.GroupLayout(uJPanel);
        uJPanel.setLayout(uJPanelLayout);
        uJPanelLayout.setHorizontalGroup(
            uJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelLayout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        uJPanelLayout.setVerticalGroup(
            uJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vJPanel.setBackground(new java.awt.Color(204, 0, 204));
        vJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/v.gif"))); // NOI18N

        javax.swing.GroupLayout vJPanelLayout = new javax.swing.GroupLayout(vJPanel);
        vJPanel.setLayout(vJPanelLayout);
        vJPanelLayout.setHorizontalGroup(
            vJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        vJPanelLayout.setVerticalGroup(
            vJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        wJPanel.setBackground(new java.awt.Color(204, 0, 204));
        wJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/w.gif"))); // NOI18N

        javax.swing.GroupLayout wJPanelLayout = new javax.swing.GroupLayout(wJPanel);
        wJPanel.setLayout(wJPanelLayout);
        wJPanelLayout.setHorizontalGroup(
            wJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        wJPanelLayout.setVerticalGroup(
            wJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        xJPanel.setBackground(new java.awt.Color(204, 0, 204));
        xJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/x.gif"))); // NOI18N

        javax.swing.GroupLayout xJPanelLayout = new javax.swing.GroupLayout(xJPanel);
        xJPanel.setLayout(xJPanelLayout);
        xJPanelLayout.setHorizontalGroup(
            xJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        xJPanelLayout.setVerticalGroup(
            xJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );

        yJPanel.setBackground(new java.awt.Color(204, 0, 204));
        yJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/y.gif"))); // NOI18N

        javax.swing.GroupLayout yJPanelLayout = new javax.swing.GroupLayout(yJPanel);
        yJPanel.setLayout(yJPanelLayout);
        yJPanelLayout.setHorizontalGroup(
            yJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        yJPanelLayout.setVerticalGroup(
            yJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        zJPanel.setBackground(new java.awt.Color(204, 0, 204));
        zJPanel.setPreferredSize(new java.awt.Dimension(84, 60));

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birthdaywishsoftware/z.gif"))); // NOI18N

        javax.swing.GroupLayout zJPanelLayout = new javax.swing.GroupLayout(zJPanel);
        zJPanel.setLayout(zJPanelLayout);
        zJPanelLayout.setHorizontalGroup(
            zJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        zJPanelLayout.setVerticalGroup(
            zJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout thirdJPanelLayout = new javax.swing.GroupLayout(thirdJPanel);
        thirdJPanel.setLayout(thirdJPanelLayout);
        thirdJPanelLayout.setHorizontalGroup(
            thirdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thirdJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(uJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(xJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(yJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(zJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        thirdJPanelLayout.setVerticalGroup(
            thirdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thirdJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thirdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(sJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(tJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(uJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(vJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(wJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(yJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(zJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainJPanelLayout = new javax.swing.GroupLayout(mainJPanel);
        mainJPanel.setLayout(mainJPanelLayout);
        mainJPanelLayout.setHorizontalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainJPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(thirdJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainJPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(secondJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(firstJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 31, Short.MAX_VALUE))
        );
        mainJPanelLayout.setVerticalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(thirdJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aJPanel;
    private javax.swing.JPanel bJPanel;
    private javax.swing.JPanel cJPanel;
    private javax.swing.JPanel dJPanel;
    private javax.swing.JPanel eJPanel;
    private javax.swing.JPanel fJPanel;
    private javax.swing.JPanel firstJPanel;
    private javax.swing.JPanel gJPanel;
    private javax.swing.JPanel hJPanel;
    private javax.swing.JPanel iJPanel;
    private javax.swing.JPanel jJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel kJPanel;
    private javax.swing.JPanel lJPanel;
    private javax.swing.JPanel mJPanel;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JPanel nJPanel;
    private javax.swing.JPanel oJPanel;
    private javax.swing.JPanel pJPanel;
    private javax.swing.JPanel qJPanel;
    private javax.swing.JPanel rJPanel;
    private javax.swing.JPanel sJPanel;
    private javax.swing.JPanel secondJPanel;
    private javax.swing.JPanel tJPanel;
    private javax.swing.JPanel thirdJPanel;
    private javax.swing.JPanel uJPanel;
    private javax.swing.JPanel vJPanel;
    private javax.swing.JPanel wJPanel;
    private javax.swing.JPanel xJPanel;
    private javax.swing.JPanel yJPanel;
    private javax.swing.JPanel zJPanel;
    // End of variables declaration//GEN-END:variables

}
