INSERT all INTO section (id_section_table, course_id, sec_id, semester, year, building, room_number, time_slot_id) VALUES(1, 'CSE300', '1', 'Fall', 2016, 'A', '309', 'A')
INTO section (id_section_table, course_id, sec_id, semester, year, building, room_number, time_slot_id) VALUES(2, 'CSE313', '2', 'Summer', 2013, 'A', '310', 'A')
INTO section (id_section_table, course_id, sec_id, semester, year, building, room_number, time_slot_id) VALUES(3, 'CSE314', '1', 'Fall', 2016, 'B', '309', 'B')
INTO section (id_section_table, course_id, sec_id, semester, year, building, room_number, time_slot_id) VALUES(4, 'ENG101', '1', 'Spring', 2013, 'C', '107', 'C')
INTO section (id_section_table, course_id, sec_id, semester, year, building, room_number, time_slot_id) VALUES(5, 'LLB102', '1', 'Summer', 2016, 'E', '422', 'A')
INTO section (id_section_table, course_id, sec_id, semester, year, building, room_number, time_slot_id) VALUES(6, 'MAT123', '2', 'Summer', 2013, 'A', '113', 'D')
INTO section (id_section_table, course_id, sec_id, semester, year, building, room_number, time_slot_id) VALUES(7, 'MAT213', '2', 'Summer', 2016, 'A', '309', 'A')
INTO section (id_section_table, course_id, sec_id, semester, year, building, room_number, time_slot_id) VALUES(8, 'PHY103', '2', 'Spring', 2014, 'A', '210', 'D')
INTO section (id_section_table, course_id, sec_id, semester, year, building, room_number, time_slot_id) VALUES(9, 'ENG101', '1', 'Fall', 2014, 'E', '501', 'C')
select * from dual;