/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vehicleparkingmenegement;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author lenovo_pc
 */
public class EditPage extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form AddPage
     */
    public EditPage() {
        initComponents();
        setVisible(true);
        setTitle("Vehicle Parking View Page");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        backJButton.addActionListener(this);
        dischargeJButton.addActionListener(this);
        searchJButton.addActionListener(this);
        
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==backJButton){
            backMethod();
        }
        if(e.getSource()==dischargeJButton){
            dischargeMethod();
        }
        if(e.getSource()==searchJButton){
            searchMethod();
        }
        
    }
    
    private void backMethod() {
        setVisible(false);
        MainPage mainPage = new MainPage();
    }
    private void dischargeMethod() {
        setVisible(false);
        DischargePage dischargePage = new DischargePage();
    }
    private void searchMethod() {
        setVisible(false);
        SearchPage searchPage = new SearchPage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundJPanel = new javax.swing.JPanel();
        footerJLabel = new javax.swing.JLabel();
        vehicleParkingMenegementJLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        doWantJLabel = new javax.swing.JLabel();
        dischargeJButton = new javax.swing.JButton();
        searchJButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));

        backgroundJPanel.setBackground(new java.awt.Color(0, 255, 255));
        backgroundJPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 255)));

        footerJLabel.setBackground(new java.awt.Color(0, 255, 153));
        footerJLabel.setFont(new java.awt.Font("Wide Latin", 3, 12)); // NOI18N
        footerJLabel.setForeground(new java.awt.Color(255, 255, 51));
        footerJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footerJLabel.setText("copyright@sabuj&nurul");

        vehicleParkingMenegementJLabel.setFont(new java.awt.Font("Viner Hand ITC", 3, 36)); // NOI18N
        vehicleParkingMenegementJLabel.setForeground(new java.awt.Color(153, 0, 153));
        vehicleParkingMenegementJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vehicleParkingMenegementJLabel.setText("VEHICLE PARKING MENEGEMENT");
        vehicleParkingMenegementJLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 255, 51)));

        backJButton.setBackground(new java.awt.Color(153, 0, 153));
        backJButton.setForeground(new java.awt.Color(255, 255, 51));
        backJButton.setText("BACK");

        doWantJLabel.setFont(new java.awt.Font("Rockwell", 3, 24)); // NOI18N
        doWantJLabel.setForeground(new java.awt.Color(255, 0, 0));
        doWantJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doWantJLabel.setText("What do you want to do?");

        dischargeJButton.setBackground(new java.awt.Color(153, 0, 153));
        dischargeJButton.setForeground(new java.awt.Color(255, 255, 51));
        dischargeJButton.setText("DISCHARGE");

        searchJButton.setBackground(new java.awt.Color(153, 0, 153));
        searchJButton.setForeground(new java.awt.Color(255, 255, 51));
        searchJButton.setText("SEARCH");

        javax.swing.GroupLayout backgroundJPanelLayout = new javax.swing.GroupLayout(backgroundJPanel);
        backgroundJPanel.setLayout(backgroundJPanelLayout);
        backgroundJPanelLayout.setHorizontalGroup(
            backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vehicleParkingMenegementJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
            .addComponent(footerJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundJPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(doWantJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dischargeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(searchJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(backgroundJPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundJPanelLayout.setVerticalGroup(
            backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundJPanelLayout.createSequentialGroup()
                .addComponent(vehicleParkingMenegementJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doWantJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dischargeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(footerJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JPanel backgroundJPanel;
    private javax.swing.JButton dischargeJButton;
    private javax.swing.JLabel doWantJLabel;
    private javax.swing.JLabel footerJLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton searchJButton;
    private javax.swing.JLabel vehicleParkingMenegementJLabel;
    // End of variables declaration//GEN-END:variables

}
