/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vehicleparkingmenegement;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author lenovo_pc
 */
public class MainPage extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        setVisible(true);
        setTitle("Vehicle Parking page main");
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        viewJButton.addActionListener(this);
        clearJButton.addActionListener(this);
        editJButton.addActionListener(this);
        saveJButton.addActionListener(this);
        
        
    }
    @Override
    public void actionPerformed(ActionEvent e) {
        
        if(viewJButton==e.getSource()){
            viewMethod();
        }
        
        if(e.getSource()==editJButton){
            editMethod();
        }
        
        if(e.getSource()==clearJButton){
            clearMethod();
        }
        
        if(e.getSource()==saveJButton){
            saveMethod();
        }
        
    }
    
    
    private void viewMethod() {
        setVisible(false);
        ViewPage viewPage = new ViewPage();
    }
    
    private void editMethod() {
        setVisible(false);
        EditPage editPage = new EditPage();
    }

    private void clearMethod() {
        serialNoJTextField.setText(null);
        nameJTextField.setText(null);
        addressJTextArea.setText(null);
        mobileNoJTextField.setText(null);
        licenseNoJTextField.setText(null);
        vehicleNoJTextField.setText(null);
        parkingTimeJTextField.setText(null);
        
    }
    
    private void saveMethod() {
        String information;
        
        String slNo = serialNoJTextField.getText();
        String nm = nameJTextField.getText();
        String address = addressJTextArea.getText();
        String mbNo = mobileNoJTextField.getText();
        String lNo = licenseNoJTextField.getText();
        String vNo = vehicleNoJTextField.getText();
        String pTime = parkingTimeJTextField.getText();
        
        information = "Serial No    : " + slNo + "\n" +
                      "Name         : " + nm + "\n" +
                      "Address      : " + address +"\n" +
                      "Mobile No    : " + mbNo + "\n" +
                      "License No   : " + lNo + "\n" +
                      "Vehicle No   : " + vNo + "\n" +
                      "Parking Time : " + pTime + "\n";
        
        System.out.println(information);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundJPanel = new javax.swing.JPanel();
        theLastSerialNoJLabel = new javax.swing.JLabel();
        lastSerialNoJTextField = new javax.swing.JTextField();
        nameJLabel = new javax.swing.JLabel();
        serialNoJLabel = new javax.swing.JLabel();
        addressJLabel = new javax.swing.JLabel();
        mobileNoJLabel = new javax.swing.JLabel();
        licenseNoJLabel = new javax.swing.JLabel();
        vehicleNoJLabel = new javax.swing.JLabel();
        parkingTimeJLabel = new javax.swing.JLabel();
        footerJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressJTextArea = new javax.swing.JTextArea();
        serialNoJTextField = new javax.swing.JTextField();
        nameJTextField = new javax.swing.JTextField();
        mobileNoJTextField = new javax.swing.JTextField();
        licenseNoJTextField = new javax.swing.JTextField();
        vehicleNoJTextField = new javax.swing.JTextField();
        parkingTimeJTextField = new javax.swing.JTextField();
        buttonJPanel = new javax.swing.JPanel();
        viewJButton = new javax.swing.JButton();
        editJButton = new javax.swing.JButton();
        clearJButton = new javax.swing.JButton();
        saveJButton = new javax.swing.JButton();
        vehicleParkingMenegementJLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.black);

        backgroundJPanel.setBackground(new java.awt.Color(0, 255, 255));
        backgroundJPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 204)));

        theLastSerialNoJLabel.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N
        theLastSerialNoJLabel.setForeground(new java.awt.Color(255, 0, 0));
        theLastSerialNoJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        theLastSerialNoJLabel.setText("The Last Serial No.");

        lastSerialNoJTextField.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N

        nameJLabel.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N
        nameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameJLabel.setText("Name                  :");

        serialNoJLabel.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N
        serialNoJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        serialNoJLabel.setText("Serial No.            :");

        addressJLabel.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N
        addressJLabel.setText("Address              :");

        mobileNoJLabel.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N
        mobileNoJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mobileNoJLabel.setText("Mobile No.         :");

        licenseNoJLabel.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N
        licenseNoJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        licenseNoJLabel.setText("License No.        :");

        vehicleNoJLabel.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N
        vehicleNoJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vehicleNoJLabel.setText("Vehicle No.        :");

        parkingTimeJLabel.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N
        parkingTimeJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        parkingTimeJLabel.setText("Parking Time     :");

        footerJLabel.setBackground(new java.awt.Color(0, 0, 255));
        footerJLabel.setFont(new java.awt.Font("Wide Latin", 3, 12)); // NOI18N
        footerJLabel.setForeground(new java.awt.Color(255, 255, 51));
        footerJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footerJLabel.setText("copyright@sabuj&nurul");

        addressJTextArea.setColumns(20);
        addressJTextArea.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N
        addressJTextArea.setRows(5);
        jScrollPane1.setViewportView(addressJTextArea);

        serialNoJTextField.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N

        nameJTextField.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N

        mobileNoJTextField.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N

        licenseNoJTextField.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N

        vehicleNoJTextField.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N
        vehicleNoJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNoJTextFieldActionPerformed(evt);
            }
        });

        parkingTimeJTextField.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N

        buttonJPanel.setBackground(java.awt.Color.orange);
        buttonJPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 87, 84), 3, true));

        viewJButton.setBackground(new java.awt.Color(204, 0, 204));
        viewJButton.setForeground(new java.awt.Color(255, 255, 51));
        viewJButton.setText("VIEW");

        editJButton.setBackground(new java.awt.Color(204, 0, 204));
        editJButton.setForeground(new java.awt.Color(255, 255, 0));
        editJButton.setText("EDIT");
        editJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJButtonActionPerformed(evt);
            }
        });

        clearJButton.setBackground(new java.awt.Color(204, 0, 204));
        clearJButton.setForeground(new java.awt.Color(255, 255, 0));
        clearJButton.setText("CLEAR");

        saveJButton.setBackground(new java.awt.Color(204, 0, 204));
        saveJButton.setForeground(new java.awt.Color(255, 255, 51));
        saveJButton.setText("SAVE");

        javax.swing.GroupLayout buttonJPanelLayout = new javax.swing.GroupLayout(buttonJPanel);
        buttonJPanel.setLayout(buttonJPanelLayout);
        buttonJPanelLayout.setHorizontalGroup(
            buttonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonJPanelLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(buttonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );
        buttonJPanelLayout.setVerticalGroup(
            buttonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonJPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(saveJButton)
                .addGap(49, 49, 49)
                .addComponent(viewJButton)
                .addGap(46, 46, 46)
                .addComponent(editJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(clearJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        vehicleParkingMenegementJLabel.setBackground(new java.awt.Color(0, 0, 0));
        vehicleParkingMenegementJLabel.setFont(new java.awt.Font("Viner Hand ITC", 3, 36)); // NOI18N
        vehicleParkingMenegementJLabel.setForeground(new java.awt.Color(153, 0, 153));
        vehicleParkingMenegementJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vehicleParkingMenegementJLabel.setText("VEHICLE   PARKING   MENEGEMENT");
        vehicleParkingMenegementJLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 255, 51)));

        javax.swing.GroupLayout backgroundJPanelLayout = new javax.swing.GroupLayout(backgroundJPanel);
        backgroundJPanel.setLayout(backgroundJPanelLayout);
        backgroundJPanelLayout.setHorizontalGroup(
            backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundJPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundJPanelLayout.createSequentialGroup()
                        .addComponent(mobileNoJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(210, 210, 210))
                    .addGroup(backgroundJPanelLayout.createSequentialGroup()
                        .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mobileNoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(backgroundJPanelLayout.createSequentialGroup()
                                .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(vehicleNoJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(parkingTimeJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(serialNoJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nameJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addressJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(licenseNoJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundJPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(parkingTimeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(backgroundJPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(serialNoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(licenseNoJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vehicleNoJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)))
                .addComponent(buttonJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(backgroundJPanelLayout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(theLastSerialNoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(lastSerialNoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(vehicleParkingMenegementJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footerJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundJPanelLayout.setVerticalGroup(
            backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundJPanelLayout.createSequentialGroup()
                .addComponent(vehicleParkingMenegementJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(theLastSerialNoJLabel)
                    .addComponent(lastSerialNoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundJPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serialNoJLabel)
                            .addComponent(serialNoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameJLabel)
                            .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundJPanelLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundJPanelLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(addressJLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(licenseNoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(licenseNoJLabel))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mobileNoJLabel)
                            .addComponent(mobileNoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicleNoJLabel)
                            .addComponent(vehicleNoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(parkingTimeJLabel)
                            .addComponent(parkingTimeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backgroundJPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(buttonJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addComponent(footerJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editJButtonActionPerformed

    private void vehicleNoJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNoJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleNoJTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressJLabel;
    private javax.swing.JTextArea addressJTextArea;
    private javax.swing.JPanel backgroundJPanel;
    private javax.swing.JPanel buttonJPanel;
    private javax.swing.JButton clearJButton;
    private javax.swing.JButton editJButton;
    private javax.swing.JLabel footerJLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastSerialNoJTextField;
    private javax.swing.JLabel licenseNoJLabel;
    private javax.swing.JTextField licenseNoJTextField;
    private javax.swing.JLabel mobileNoJLabel;
    private javax.swing.JTextField mobileNoJTextField;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JLabel parkingTimeJLabel;
    private javax.swing.JTextField parkingTimeJTextField;
    private javax.swing.JButton saveJButton;
    private javax.swing.JLabel serialNoJLabel;
    private javax.swing.JTextField serialNoJTextField;
    private javax.swing.JLabel theLastSerialNoJLabel;
    private javax.swing.JLabel vehicleNoJLabel;
    private javax.swing.JTextField vehicleNoJTextField;
    private javax.swing.JLabel vehicleParkingMenegementJLabel;
    private javax.swing.JButton viewJButton;
    // End of variables declaration//GEN-END:variables

    
}
