/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package aboutbangladesh;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author Hridoy Ghoush Anik
 */
public class Before71 extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Before71
     */
    
    public String path;
    
    public Before71() {
        initComponents();
        setVisible(true);
        setTitle("This is Before-1971 Page ..");
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        backJButton.addActionListener(this);
        j52Button.addActionListener(this);
        j62Button.addActionListener(this);
        j66Button.addActionListener(this);
        j69Button.addActionListener(this);
        j70Button.addActionListener(this);
        j71Button.addActionListener(this);
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        
        if(e.getSource()==backJButton){
            setVisible(false);
            HistoryPage historyPage = new HistoryPage();
        }
        if(e.getSource()==j52Button){
            method1952();
        }
        if(e.getSource()==j62Button){
            method1952();
        }
        if(e.getSource()==j66Button){
            method1952();
        }
        if(e.getSource()==j69Button){
            method1952();
        }
        if(e.getSource()==j70Button){
            method1952();
        }
        if(e.getSource()==j71Button){
            method1952();
        }
        
    }
    
    private void method1952() {
        path = "file-1952.txt";
        String show = fileReadMethod(path);
        ShowFrame showFrame = new ShowFrame(show);
    }
    
    
    
    private String fileReadMethod(String p){
        
        StringBuilder sb = new StringBuilder();
        BufferedReader br = null;
        try {
            br = new BufferedReader(new FileReader(p));
            String line;
            while ((line = br.readLine()) != null) {
                if (sb.length() > 0) {
                    sb.append("\n");
                }
                sb.append(line);
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                if (br != null) {
                    br.close();
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        String contents = sb.toString();
        //System.out.println(contents);
        
        return contents;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundJPanel = new javax.swing.JPanel();
        titleJLabel = new javax.swing.JLabel();
        buttonJPanel = new javax.swing.JPanel();
        j52Button = new javax.swing.JButton();
        j62Button = new javax.swing.JButton();
        j66Button = new javax.swing.JButton();
        j69Button = new javax.swing.JButton();
        j70Button = new javax.swing.JButton();
        j71Button = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundJPanel.setBackground(new java.awt.Color(0, 0, 0));
        backgroundJPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 255, 204)));

        titleJLabel.setFont(new java.awt.Font("Papyrus", 3, 36)); // NOI18N
        titleJLabel.setForeground(new java.awt.Color(0, 255, 51));
        titleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleJLabel.setText("Road To Freedom");
        titleJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        buttonJPanel.setBackground(new java.awt.Color(0, 255, 255));
        buttonJPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 0)));

        j52Button.setBackground(new java.awt.Color(255, 0, 255));
        j52Button.setFont(new java.awt.Font("Vivaldi", 3, 24)); // NOI18N
        j52Button.setForeground(new java.awt.Color(0, 153, 153));
        j52Button.setText("1952");

        j62Button.setBackground(new java.awt.Color(255, 0, 255));
        j62Button.setFont(new java.awt.Font("Vivaldi", 3, 24)); // NOI18N
        j62Button.setForeground(new java.awt.Color(0, 153, 153));
        j62Button.setText("1962");

        j66Button.setBackground(new java.awt.Color(255, 0, 255));
        j66Button.setFont(new java.awt.Font("Vivaldi", 3, 24)); // NOI18N
        j66Button.setForeground(new java.awt.Color(0, 153, 153));
        j66Button.setText("1966");

        j69Button.setBackground(new java.awt.Color(255, 0, 255));
        j69Button.setFont(new java.awt.Font("Vivaldi", 3, 24)); // NOI18N
        j69Button.setForeground(new java.awt.Color(0, 153, 153));
        j69Button.setText("1969");
        j69Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j69ButtonActionPerformed(evt);
            }
        });

        j70Button.setBackground(new java.awt.Color(255, 0, 255));
        j70Button.setFont(new java.awt.Font("Vivaldi", 3, 24)); // NOI18N
        j70Button.setForeground(new java.awt.Color(0, 153, 153));
        j70Button.setText("1970");

        j71Button.setBackground(new java.awt.Color(255, 0, 255));
        j71Button.setFont(new java.awt.Font("Vivaldi", 3, 24)); // NOI18N
        j71Button.setForeground(new java.awt.Color(0, 153, 153));
        j71Button.setText("1971");

        javax.swing.GroupLayout buttonJPanelLayout = new javax.swing.GroupLayout(buttonJPanel);
        buttonJPanel.setLayout(buttonJPanelLayout);
        buttonJPanelLayout.setHorizontalGroup(
            buttonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonJPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(buttonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(j52Button, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(j69Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addGroup(buttonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j62Button, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j70Button, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(buttonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(j66Button, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(j71Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        buttonJPanelLayout.setVerticalGroup(
            buttonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonJPanelLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(buttonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j52Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j62Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j66Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(buttonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j70Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j71Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j69Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        backJButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(51, 51, 255));
        backJButton.setText("BACK");

        javax.swing.GroupLayout backgroundJPanelLayout = new javax.swing.GroupLayout(backgroundJPanel);
        backgroundJPanel.setLayout(backgroundJPanelLayout);
        backgroundJPanelLayout.setHorizontalGroup(
            backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(backgroundJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundJPanelLayout.setVerticalGroup(
            backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundJPanelLayout.createSequentialGroup()
                .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j69ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j69ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j69ButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JPanel backgroundJPanel;
    private javax.swing.JPanel buttonJPanel;
    private javax.swing.JButton j52Button;
    private javax.swing.JButton j62Button;
    private javax.swing.JButton j66Button;
    private javax.swing.JButton j69Button;
    private javax.swing.JButton j70Button;
    private javax.swing.JButton j71Button;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables

    

    
}
